kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: workdir
spec:
  accessModes: 
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi # make this bigger in production
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: s3x
  labels:
    name: s3x
    app: s3x
spec:
  replicas: 2
  selector:
    matchLabels:
      app: s3x
  template:
    metadata:
      labels:
        app: s3x
        role: gateway
    spec:
      volumes:
        - name: workdir
          persistentVolumeClaim:
            claimName: workdir
      containers:
        - name: s3x
          image: rtradetech/s3x-test:latest
          args: ["gateway", "s3x", "--temporalx.insecure"]
          env:
            - name: MINIO_ACCESS_KEY
              value: minio
            - name: MINIO_SECRET_KEY
              value: minio123
          ports:
            - name: api-s3x
              containerPort: 9000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: s3x-service
  labels:
    app: s3x
spec:
  type: LoadBalancer
  ports:
    - name: api-s3x
      targetPort: api-s3x
      port: 9000
  selector:
    app: s3x
