apiVersion: apps/v1
kind: Deployment
metadata:
    name: s3x
spec:
    selector:
        matchLabels:
            app: s3x
    replicas: 2
    template:
        metadata:
            labels:
                app: s3x
        spec:
            containers:
                - name: s3x
                  image: rtradetech/s3x-test
                  args: ["gateway", "s3x", "--temporalx.endpoint", "localhost:9090", "--temporalx.insecure"]
                  env:
                    - name: MINIO_ACCESS_KEY
                      value: minio
                    - name: MINIO_SECRET_KEY
                      value: minio123
                  ports:
                    - containerPort: 9000
                - name: temx
                  image: temporalx:latest
                  imagePullPolicy: Never
                  args: ["server"]
                  ports:
                    - containerPort: 9090
                    - containerPort: 4005